name: GenerateDocs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.

      - name: pull protoc-gen-docs
        run:  |
          go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc

      - name: Compile Documentation
        run:  |
          mkdir pages
          protoc --doc_out=./pages --doc_opt=html,index.html ./*.proto

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      