name: NPM Package
  
on:  
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./libs/node

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - run: |
          version=$(echo ${{ steps.version.outputs.release }} | cut -c 1-)
          echo "::set-output name=version::$version"

      - name: update version
        run:  |
            cd ./libs/node
            npm version ${{ steps.get-version-sem.outputs.version }}

      - run: |
          cp ../../README.md ./README.md
          cd ./libs/node
          npm version minor --force

      - run: npm i -g protobufjs

      - name: Generate JS Module
        run: pbjs -t static-module -w es6 --es6 -o mirabuf.js ../../*.proto --no-beautify --no-comments

      - name: Generate TS Bindings
        run: pbts -o mirabuf.d.ts mirabuf.js

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "./libs/node/package.json"
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true

      - if: steps.publish.outputs.type != 'none'
        run: |
            echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"