name: NPM Package
  
on:  
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./libs/node

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - name: update version
        run:  |
            npm version ${{ steps.version.outputs.release }} --no-git-tag-version --allow-same-version

      - run: |
          cp ../../README.md ./README.md

      - run: npm i -g protobufjs

      - name: Generate JS Module
        run: pbjs -t static-module -w commonjs -o mirabuf.js ../../*.proto

      - name: Generate TS Bindings
        run: pbts -o mirabuf.d.ts mirabuf.js

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "./libs/node/package.json"
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false

      - if: steps.publish.outputs.type != 'none'
        run: |
            echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"