name: BuildProto
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Python Libs
        run:  |
           protoc -I=. --python_out=./libs/python ./*.proto
           ls ./libs/python -R

      - uses: actions/upload-artifact@v2
        with:
          name: python_proto_artifact
          path: ./libs/python/
          if-no-files-found: error

      - name: Cpp Libs
        run:  |
           protoc -I=. --cpp_out=./libs/cpp ./*.proto
           ls ./libs/cpp -R

      - uses: actions/upload-artifact@v2
        with:
          name: cpp_proto_artifact
          path: ./libs/cpp/
          if-no-files-found: error

      - name: Java Libs
        run:  |
           protoc -I=. --java_out=./libs/java ./*.proto
           ls ./libs/java -R

      - uses: actions/upload-artifact@v2
        with:
          name: java_proto_artifact
          path: ./libs/java/
          if-no-files-found: error

      - name: Print Libs
        run:  |
           ls ./libs -R
